baseURL = "https://971103.xyz"
languageCode = "en-us"
title = "Home"
theme = "rocinante-2"
paginate = 9999
summaryLength = 0

[markup]
  [markup.highlight]
    tabWidth = 2
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true

[params]
  colorScheme = "auto"
  customCSS = ["/css/style.css"]
  favicon = "/icons/favicon.ico"
  socialBanner = "/icons/banner.png"
  mainSections = ["posts", "photos"]
  specialEmail = "yundongzhang97@gmail.com"
  about = """
Hey there! I'm <b class="sway">Yundong</b>,

and this is my little corner of the internet. Feel free to take a look around, but please leave your shoes at the door!

I'm a software engineer by profession, with a passion for learning new things, tinkering with electronics, and working on building a decentralized internet.

I love dota2, music, art, and the world we live in.
If you're interested in collaborating, _or if you just want to chat, feel free to <a href="mailto:yundongzhang97@gmail.com">email</a> me!_

<a style="text-decoration-line: underline; text-decoration-style: wavy;" href="https://ipscaner.com" target="_blank" rel="noopener noreferrer">ipscaner.com</a>
<br>
"""
